### ISSUE TITLE
Use new dxvk-async (with gpl).

### ISSUE THREAD

**Issue by begin-theadventure** [cyrv6737/NorthstarProton#11]
Fork (dxvk-gplasync) that made async work with the graphics pipeline library and the latest version of DXVK:
https://github.com/Sporif/dxvk-async/issues/64#issuecomment-1441560713

**Comment by SA64BD** [comment]
Thanks alot. No issues so far

**Comment by cyrv6737** [comment]
I'll take a look at switching to this fork once I'm ready to release a new build (likely based on wine-staging 8.2 or 8.3). Thanks for bringing this to my attention!

In the meantime, anyone that wants to use this fork can just drop in and replace the DXVK binaries packaged with NorthstarProton and it should work without issue.

Once GPL is fully completed and merged into RADV, NorthstarProton will move to regular DXVK, either based on master at time of build or latest release.
