### ISSUE TITLE
Cannot launch game with NorthstarProton on Steam Deck

### ISSUE THREAD

**Issue by lejvin** [cyrv6737/NorthstarProton#12]
Hello, the game will not launch at all with NorthstarProton on my steam deck (Nothing pops up). I have tried this already:

- Downgrading to 7.21
- Reinstalling Northstar
- Installing corefonts, d3dcompiler_43, d3dcompiler_47
- Deleting compatdata/1237970

None of these things made any difference. Here is the proton log: 

[steam-1237970.log](https://github.com/cyrv6737/NorthstarProton/files/11239751/steam-1237970.log)

**Comment by lejvin** [comment]
Noticing that this issue is quite similar to #1, I am using the EA app though, since origin is now obsolete.

**Comment by bungholemaster** [comment]
I'm having the same issue, have you managed to get it working at all?

Game will boot for me normally through proton experimental but just does nothing with northstar proton. Clearing the compatdata folder doesn't help.

**Comment by lejvin** [comment]
> I'm having the same issue, have you managed to get it working at all?
> 
> Game will boot for me normally through proton experimental but just does nothing with northstar proton. Clearing the compatdata folder doesn't help.

Hi, sorry for not updating. I did manage to get it working eventually. What I ended up doing was **deleting** the compatdata/1237970 folder. I think that's what I had done previously. But I might also just have cleared the contents of the folder. Either way, closing steam and deleting it worked. Closing this issue now.

**Comment by bungholemaster** [comment]
> > I'm having the same issue, have you managed to get it working at all?
> > Game will boot for me normally through proton experimental but just does nothing with northstar proton. Clearing the compatdata folder doesn't help.
> 
> Hi, sorry for not updating. I did manage to get it working eventually. What I ended up doing was **deleting** the compatdata/1237970 folder. I think that's what I had done previously. But I might also just have cleared the contents of the folder. Either way, closing steam and deleting it worked. Closing this issue now.

Deleting the compatdata doesn't get it to work for me.

It still doesn't launch through northstar proton at all.

**Comment by bungholemaster** [comment]
> > I'm having the same issue, have you managed to get it working at all?
> > Game will boot for me normally through proton experimental but just does nothing with northstar proton. Clearing the compatdata folder doesn't help.
> 
> Hi, sorry for not updating. I did manage to get it working eventually. What I ended up doing was **deleting** the compatdata/1237970 folder. I think that's what I had done previously. But I might also just have cleared the contents of the folder. Either way, closing steam and deleting it worked. Closing this issue now.

Also forgot to ask, when you booted the game after deleting the folder did you do it vanilla with proton experimental first?

**Comment by lejvin** [comment]
Okay, I retested it today and i also couldn't get it to launch through NorthstarProton. My fix was using protontricks to install the DLL libraries `d3dcompiler_43` and `d3dcompiler_47`. Then launching the game immediately worked.

It seems to me that it was a combination of these missing libraries and something messy in the compatdata folder that caused the game not to launch. Let me know if this works for you!

**Comment by bungholemaster** [comment]
> Okay, I retested it today and i also couldn't get it to launch through NorthstarProton. My fix was using protontricks to install the DLL libraries `d3dcompiler_43` and `d3dcompiler_47`. Then launching the game immediately worked.
> 
> It seems to me that it was a combination of these missing libraries and something messy in the compatdata folder that caused the game not to launch. Let me know if this works for you!

Did you install those after running the game through proton experimental/vanilla first?
