### ISSUE TITLE
NorthstarProton doesn't start

### ISSUE THREAD

**Issue by benjiae** [cyrv6737/NorthstarProton#4]
OS: Gentoo Linux (OpenRC), using steam-launcher from steam-overlay

Hi, i'm following the linux guide from the [Northstar page](https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/playing-on-linux), and when i open titanfall 2 on steam it stays at open for like 0.5 secs and then closes, i've tried to use the "PROTON_LOG=1 %command%" launch argument and it doesn't leave a log, [here is the log that steam does when starting from terminal](https://gist.github.com/benjiae/25fe04337f46989be13337a092311fa5)

**Comment by cyrv6737** [comment]
Try the following:
1) Reinstall NorthstarProton completely
2) Delete titanfall 2 compatdata / proton prefix
3) Start the game and see if anything changes

**Comment by benjiae** [comment]
it didn't change anything, but i figured out by copying the ntdll.so from `files/lib64/wine/x86_64-unix/ntdll.so` to `files/lib64/ntdll.so` that libunwind was missing, i installed it (sys-libs/libunwind) and now it works :)

**Comment by cyrv6737** [comment]
Thats great to hear! I'll close this issue now and make a note of this.
